# Generated by Django 3.2.4 on 2022-06-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnotes',
            name='note',
            field=models.CharField(default='https://res.cloudinary.com/dsru0cxgv/image/upload/v1656336668/q3kx3af4qxhxwtbqckin.jpg', max_length=1000),
        ),
    ]
